# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c5e0eedaeb3aba78ac69c3e70a7ef550219c6e766d93e20d7db2fddaa2d2d66ac9019d0343794a6254044df74965af2ef464c9950c3634cb3714c8ba370dc99a

test:
  secret_key_base: 28ba0d430cd27142ecb734a7c60ff5bb3ab5defc69e9989e279e7599fc9617e366b7a109407888beaf27c1fe71014313ce7fb666093f2075e40bd3588d4217b8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
